name: Android CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Android Test Report Action
      # You may pin to the exact commit or the version.
      # uses: asadmansr/android-test-report-action@384cd31388782f4106dc4a1b37eea2ff02e0aad7
      uses: asadmansr/android-test-report-action@v1.2.0
